#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
# Source0 file verified with key 0x3602B07F55D0C732 (gray@gnu.org)
#
Name     : tar
Version  : 1.35
Release  : 39
URL      : https://mirrors.kernel.org/gnu/tar/tar-1.35.tar.xz
Source0  : https://mirrors.kernel.org/gnu/tar/tar-1.35.tar.xz
Source1  : https://mirrors.kernel.org/gnu/tar/tar-1.35.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0 GPL-3.0+
Requires: tar-bin = %{version}-%{release}
Requires: tar-info = %{version}-%{release}
Requires: tar-libexec = %{version}-%{release}
Requires: tar-license = %{version}-%{release}
Requires: tar-locales = %{version}-%{release}
Requires: tar-man = %{version}-%{release}
Requires: xz-bin
Requires: zstd-bin
BuildRequires : acl-dev
BuildRequires : bison
BuildRequires : buildreq-configure
BuildRequires : glibc-locale
BuildRequires : glibc-staticdev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: timestamp.patch
Patch2: blocking.patch

%description
See the end of file for copying conditions.
* Introduction
Please glance through *all* sections of this
'ABOUT-NLS' and 'INSTALL' if you are not familiar with them already.

%package bin
Summary: bin components for the tar package.
Group: Binaries
Requires: tar-libexec = %{version}-%{release}
Requires: tar-license = %{version}-%{release}

%description bin
bin components for the tar package.


%package info
Summary: info components for the tar package.
Group: Default

%description info
info components for the tar package.


%package libexec
Summary: libexec components for the tar package.
Group: Default
Requires: tar-license = %{version}-%{release}

%description libexec
libexec components for the tar package.


%package license
Summary: license components for the tar package.
Group: Default

%description license
license components for the tar package.


%package locales
Summary: locales components for the tar package.
Group: Default

%description locales
locales components for the tar package.


%package man
Summary: man components for the tar package.
Group: Default

%description man
man components for the tar package.


%prep
%setup -q -n tar-1.35
cd %{_builddir}/tar-1.35
%patch -P 1 -p1
%patch -P 2 -p1
pushd ..
cp -a tar-1.35 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1689700522
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%reconfigure --disable-static
make  %{?_smp_mflags}
unset PKG_CONFIG_PATH
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3"
%reconfigure --disable-static
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :
cd ../buildavx2;
make %{?_smp_mflags} check || : || :

%install
export SOURCE_DATE_EPOCH=1689700522
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/tar
cp %{_builddir}/tar-%{version}/COPYING %{buildroot}/usr/share/package-licenses/tar/31a3d460bb3c7d98845187c716a30db81c44b615 || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
%find_lang tar
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/tar
/usr/bin/tar

%files info
%defattr(0644,root,root,0755)
/usr/share/info/tar.info
/usr/share/info/tar.info-1
/usr/share/info/tar.info-2
/usr/share/info/tar.info-3

%files libexec
%defattr(-,root,root,-)
/V3/usr/libexec/rmt
/usr/libexec/rmt

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/tar/31a3d460bb3c7d98845187c716a30db81c44b615

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/tar.1
/usr/share/man/man8/rmt.8

%files locales -f tar.lang
%defattr(-,root,root,-)

